### ISSUE TITLE
Cannot find module 'set-interval-async/dynamic' or its corresponding type declarations.

### ISSUE THREAD

**Issue by kevcodez** [ealmansi/set-interval-async#42]
After upgrading to 3.0.1, I am getting the following error:

```ts
import { setIntervalAsync } from 'set-interval-async/dynamic';
```

> Cannot find module 'set-interval-async/dynamic' or its corresponding type declarations.

Importing from `set-interval-async` without the dynamic suffix works fine.
